---
- name: Check that kubernetes is alredy installed
  hosts: all
  roles:
    - check-kubernetes-installation

- name: Upgrade kube on masters
  hosts: masters
  serial: 1
  roles: 
    - upgrade-k8s-master

- name: upgrade kubeadm on workers
  hosts: workers
  roles: 
    - upgrade-kubeadm-worker-nodes

- name: upgrade kubelet, kubectl on every worker one at a time
  hosts: workers
  serial: 1
  roles: 
    - upgrade-kube-workers
  #tasks:
  #  - name: Run role tasks on every host one at time
  #    include_tasks: ./roles/update-kube-workers/tasks/main.yml
        

  
  
  
