---
# tasks file for configuration-before-install-k8s
- name: Create containerd.conf
  become: yes
  file: 
    path: /etc/modules-load.d/containerd.conf 
    state: touch
- name: load modules overlay and br_netfilter
  become: yes
  blockinfile:
    path: /etc/modules-load.d/containerd.conf
    insertafter: EOF
    block: |
      br_netfilter
      overlay

- name: load overlay module
  become: yes
  modprobe: 
    name: overlay
    state: present

- name: load br_netfilter module
  become: yes
  modprobe: 
    name: br_netfilter
    state: present

- name: Create file /etc/99-kubernetes-cri.conf
  become: yes
  file: 
    path: /etc/99-kubernetes-cri.conf
    state: touch
  
- name: add sysctl net.bridge.bridge-nf-call-iptables 
  become: yes
  sysctl: 
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present
    sysctl_file: /etc/99-kubernetes-cri.conf

- name: add sysctl net.ipv4.ip_forward
  become: yes 
  sysctl: 
    name: net.ipv4.ip_forward
    value: 1
    state: present
    sysctl_file: /etc/99-kubernetes-cri.conf

- name: add sysctl net.bridge.bridge-nf-call-ip6tables
  become: yes
  sysctl: 
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    state: present
    sysctl_file: /etc/99-kubernetes-cri.conf

- name: Reload configuration 
  become: yes
  command: 
    cmd: sysctl --system