---
# tasks file for init-k8s-master
- name: Initializing k8s master node
  become: yes
  command: kubeadm init --pod-network-cidr 192.168.0.0/16 --kubernetes-version 1.22.0

- name: Creating .kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755
  
- name: Configuring users cluster access
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ansible/.kube/config
    remote_src: yes
    owner: ansible

- name: Configuring ansible user to use kubelet 
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ansible/admin.conf
    remote_src: yes
    owner: ansible

- name: export varible to use admin conf
  lineinfile: dest=/home/ansible/.bashrc line='export KUBECONFIG=$HOME/admin.conf' insertafter='EOF' state=present

- name: Installing Pod network…. (Calico)
  shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml 

