---
# tasks file for update-kubeadm-on-primary-controlplane
- name: unmark hold kubeadm
  become: yes
  dpkg_selections:
    name: kubeadm
    selection: hold

#- name: update kubeadm on primary control node
#  become: yes
#  apt: 
#    name: kubeadm={{new_version_k8s_desired}}
#    state: present
#    update_cache: yes


